### ISSUE TITLE
Implement change proposals in language (nested namespaces)

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/vsc-tools#17]
Implement changes in namespaces:
https://github.com/GENIVI/vehicle_service_catalog/pull/4

**Comment by erikbosch** [comment]
As the chnanes in vsc now has been merged this issue can be rephrased to "Adapt vsc-tools to recent vsc changes" or similar

**Comment by gunnarx** [comment]
Renamed for clarity.
If all proposed feature changes are now supported then this can be closed?

**Comment by gunnarx** [comment]
Closing issue as it is replaced by PR #21
